### ISSUE TITLE
API suggestions

### ISSUE THREAD

**Issue by Radiergummi** [fresheneesz/drip-drop#1]
I've just found this project and it looks promising (anything preventing me from having to deal with the native API is promising as hell), but I find the API to be mildly... weird. Looking at your example:

````js
var dd = require("drip-drop")
````
looks great so far.

````js
dd.drag(myDomNode, {
````
how about `new dd.Draggable(myDomNode, options)` instead? Seems a little more obvious to me.

````js
    dragImage: true, // default drag image
    start: function(setData, e) {
        setData('myCustomData', JSON.stringify({a:1, b:"NOT THE BEES"})) // camel case types are allowed!*
    }
})
````
instead of `setData`, why not pass a `data` object to the start callback which you can append new values to? We're in the golden ages of JS right now and can even use `Object.assign()` 😄 

````js
dd.drop(myDropzone, {
````
same as above - `new dd.Dropzone(myDomNode, options)` maybe?

````js
    drop: function(data, e) {
        myDropzone.innerHTML = data.myCustomData
    }
})
````

Or by using one of the available `EventEmitter` libraries and provide just the following:

````js
let dropZone = new DripDrop(myDomNode, options);

dropZone.on('drag', (data, event) => Object.assign(data, {
  myCustomData: JSON.stringify({a:1, b:"BUT I LOVE BEES"})
}));

dropZone.on('idle', stoppedDragging);
dropZone.on('drop', droppedSomething);
// ...
````
...and so on. I know dragging and dropping can be used for different things, but usually, if you provide drag functionality, you want something to happen if things are dropped again so combining both in the same instance would make sense.  
What do you think?

**Comment by fresheneesz** [comment]
"`new dd.Draggable(myDomNode, options)`"

This sounds more like a class to me. I'd expect something like that to return an object instance that has methods and represents the draggable thing. The return value of `dd.drag` doesn't represent any draggable thing and doesn't have methods - its just a clean up function. So I don't think that is the right semantics. 

"why not pass a data object to the start callback which you can append new values to? "

I suppose that could be done.

"using one of the available EventEmitter libraries"

I like the last API you suggested. I have a nagging feeling that some of that might be a bit hard to do given the absurd hoops this has to jump through to satisfy the native API's requirements. But I can't think of a good reason at the moment why it couldn't be done. I would be open to accepting a pull request for an API like that, tho I'd want to sign off on a more full spec first.

**Comment by Radiergummi** [comment]
I'll see what I can up with this weekend 👍

**Comment by Radiergummi** [comment]
Hey @fresheneesz, I rewrote the library to ES6 and moved the event callbacks to use an `EventEmitter`. Because I didn't have the time to update building and tests yet, I didn't create a PR but a gist instead: https://gist.github.com/Radiergummi/aba408acd53573f570a8e44d914b210d
There might be serious mistakes, it might not be working at all, but that's what I imagine the API  to be, so maybe have a look at it and tell me what you think 😄

**Comment by fresheneesz** [comment]
Hey @Radiergummi , thanks for the work. Its really hard for me to see what you changed since this is a new repo rather than a modification of a previous file. But it looks like the API you're proposing is something like:

var draghandle = DripDrop.drag(domNode, options)
var dropzone = DripDrop.drop(domNode, options)

draghandle.on("start", function(){...})

dropzone.on("enter", function(){...})
dropzone.on("in", function(){...})
dropzone.on("leave", function(){...})
dropzone.on("out", function(){...})
dropzone.on("drop", function(){...})

**Comment by fresheneesz** [comment]
Oops, sorry posted early. 

This code seems to leave out a couple events the current version has: drag move, drag end, and drop move.  Let me take a stab at doing this this weekend, with your code as a guide.

**Comment by Radiergummi** [comment]
Hey,
Yep, this has become pretty different to the original... Since I wanted to make DripDrop instances that inherit from EventEmitter, I decided to rewrite the files as ES6 classes, that changed pretty much.  
On first sight! Basically, everything works mostly as it used to, you can also still pass event callbacks to the constructor as they are automatically attached.
But due to the EventEmitter prototype, you can use `instance.on(eventName)`. 

Some things are still missing but I didn't have time to finish yet, such as the missing events. I wanted to know what you think anyway 😉

**Comment by Radiergummi** [comment]
...and  `instance.off` to remove listeners or `instance.emit` to manually trigger them

**Comment by fresheneesz** [comment]
I'll probably inherit EventEmitter using `proto` to minimize changes. Changing to this API shouldn't be hard, but I also want to preserve (and deprecate) the previous API for backwards compatibility.

**Comment by fresheneesz** [comment]
Just committed the changes. Should be all good to go! Thanks!
